APPROVED = 'APPROVED'
AWAITING_REVIEW = 'AWAITING REVIEW'
STUDY_ID = 'STUDY_ID'
PROLIFIC_PID = 'PROLIFIC_PID'
MAJ_RESP_COUNT = 'MAJ_RESP_COUNT'
MIN_RESP_COUNT = 'MIN_RESP_COUNT'
MAJ_STD_ID = 'MAJ_STD_ID'
MIN_STD_ID = 'MIN_STD_ID'
MAJ_APPROVED = 'MAJ_APPROVED'
MIN_APPROVED = 'MIN_APPROVED'
SKIP_ROWS = [2]

COMPLETION_CODE = '19AE28A9'

